name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # Update as per your setup
      EKS_CLUSTER: Final-Project
      IMAGE_TAG: latest
      NAMESPACE: otel-demo

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/opentelemetry-demo:${{ env.IMAGE_TAG }} .

    # - name: Push Docker image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/opentelemetry-demo:${{ env.IMAGE_TAG }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE
